// Generated by Xata Codegen 0.29.4. Please do not edit.
import { buildClient } from "@xata.io/client"
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "requests",
    columns: [
      { name: "applicant", type: "json" },
      { name: "contact", type: "string" },
      { name: "reason", type: "string" },
      { name: "time", type: "string" },
      { name: "isApproved", type: "bool" },
      { name: "ip", type: "text" },
      { name: "status", type: "text" },
      { name: "fcm", type: "string" },
    ],
  },
  {
    name: "admin_tokens",
    columns: [
      { name: "token", type: "text" },
      { name: "label", type: "string" },
      { name: "lastValidatedAt", type: "datetime" },
    ],
  },
]
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient()
const defaultOptions = {
  databaseURL: "https://pr-citrate-s-workspace-piheva.ap-southeast-2.xata.sh/db/sunja-approve",
  branch: process.env.XATA_BRANCH ?? "main",
  apiKey: process.env.XATA_API_KEY,
}
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables)
  }
}
let instance
/**
 * @param {{ forceNew?: boolean } & import('@xata.io/client').ClientOptions} [options]
 * @returns {XataClient}
 */
export const getXataClient = (options = {}) => {
  const { forceNew = false, ...clientOptions } = options
  if (instance && !forceNew) return instance
  if (!defaultOptions.apiKey && !clientOptions.apiKey) {
    console.warn(
      "[xata] Missing XATA_API_KEY environment variable. API calls will fail until it is configured.",
    )
  }
  instance = new XataClient(clientOptions)
  return instance
}

export const resetXataClient = () => {
  instance = undefined
}
